language: node_js
node_js:
  - '0.12'
  - '0.10'
  - '6'
before_install:
  - npm install -g grunt-cli bower
install:
  - bower install
  - npm install
after_success:
  - '[ -n "$TRAVIS_TAG" ] && git add dist/ && git commit -m "Add dist/ folder to the tag" && git tag -d $TRAVIS_TAG && git tag $TRAVIS_TAG && git push origin :$TRAVIS_TAG && git push origin $TRAVIS_TAG'
