language: node_js
node_js:
  - '0.12'
  - '0.10'
  - '6'
before_install:
  - npm install -g grunt-cli bower
install:
  - bower install
  - npm install
after_success:
  - echo foo
  - echo $TRAVIS_TAG
  - '[ -n "$TRAVIS_TAG" ] && echo toto'
